default_platform(:ios)

lane :travis do
  cocoapods(
    repo_update: true,
    podfile: "./Example/"
  )
  run_tests(
    workspace: "Example/SwiftBTC.xcworkspace",
    scheme: "SwiftBTC-Example"
  )
  pod_lib_lint
end

desc "Releases the framework"
desc "This lane should be run from your local machine."
desc " * Verifies the git branch is clean"
desc " * Ensures the lane is running on the master branch"
desc " * Pulls the remote to verify the latest the branch is up to date"
desc " * Updates the version of the info plist path used by the framework"
desc " * Updates the the version of the podspec"
desc " * Commits the changes"
desc " * Pushes the commited branch"
desc " * Creates a tag"
desc " * Pushes the tag"
desc " * Pushes podspec to pod trunk"
desc "####Example:"
desc "```\nfastlane prepare_framework_release version:3.0.0\n```"
desc ""
lane :release_framework do |options|
  if !options[:version] 
    UI.user_error!("No version specified!") 
  end
  
  #Ensure the branch is clean
  ensure_git_status_clean
  
  #Ensure we are on the right branch
  ensure_git_branch(branch: "master")
  
  #Pull the latest to ensure we are up to date
  sh("git pull origin master")
  
  #Update the podspec
  version_bump_podspec(
    path: "SwiftBTC.podspec",
    version_number: options[:version]
  )
        
  # commit the branch
  git_commit(
    path: ".",
    message: "pod: Preparing for the #{options[:version]} release"
  )

  #push the branch
  push_to_git_remote(remote: "origin")
    
  # tag the repo
  add_git_tag(tag: "#{options[:version]}")

  # push the tag
  push_git_tags()

  #pod trunk push
  pod_push
end
